### PR TITLE
Update/grant privilege

### PR DESCRIPTION
**Pull request by Kazdan1994**
Hi,

I make some changes :

* Update dependencies to use the latest stable strapi version ;
* I rewrite the grantPrivilege in order to support collections name with '-', like todo-list
* I add a script in packages.json for watching changes in test

Thank you for your feedback

### CODE REVIEW

**Comment by qunabu** [comment]
Thanks for that. I need to update this sooner then later because there are many update in the strapi. 

Will have a look on this

**Comment by Kazdan1994** [comment]
Thanks to you. I try to share my experience in integration testing with strapi and jest. Hope it work.

**Comment by qunabu** [comment]
I'll replace CircleCI with Github Actions #43 but right now CI does throw this issue 

```
Error: expected 200 "OK", got 403 "Forbidden"
    at Object.<anonymous> (/home/circleci/project/tests/todo-list/index.js:15:8)
```

Can you have a look on those ⬆️

**Comment by Kazdan1994** [comment]
Hi. After review, jest need to be freeze at 26.6.3, all version >= 27.0.0 cause open handles and memory leaks. I opened an issue about that : [https://github.com/facebook/jest/issues/11649](https://github.com/facebook/jest/issues/11649).

Have a nice day.

**Comment by qunabu** [comment]
great job, will have a look on those soon

**Comment by qunabu** [comment]
@Kazdan1994 can you update the code with latest `main` branch , then i can merge this. I can't now because there are conficts

**Comment by Kazdan1994** [comment]
Happy new year 2022. Sorry I was on vacation without computer. So I'm back and I merged your main branch. All tests pass.

Thank you for review.

**Comment by qunabu** [comment]
@Kazdan1994 I've just updated the main branch to v4 - it's huge progress in my opinion. 

Would you consider rewrite you examples into v4 version?

**Comment by Kazdan1994** [comment]
Hi.

I'm working on a new strapi project on v4 and add testing on it. So I could share my work in a few time.

Stay tuned.

**Comment by qunabu** [comment]
@Kazdan1994 you can see that this project is already updated the more examples the better imho

**Pull request merged**
